export const HANDLE_AUTH_INPUT = 'HANDLE_INPUT';
export const HANDLE_AUTH_SUBMIT = 'HANDLE_AUTH_SUBMIT';
export const HANDLE_AUTH_SUCCESS = 'HANDLE_AUTH_SUCCESS';
export const HANDLE_AUTH_FAILED = 'HANDLE_AUTH_FAILED';
