export const HANDLE_AUTH_INPUT = 'HANDLE_INPUT';
export const HANDLE_AUTH_SUBMIT = 'HANDLE_AUTH_SUBMIT';
export const HANDLE_AUTH_SUCCESS = 'HANDLE_AUTH_SUCCESS';
export const HANDLE_AUTH_FAILED = 'HANDLE_AUTH_FAILED';
export const HANDLE_CLEAR_AUTH_STATE = 'HANDLE_CLEAR_AUTH_STATE';
/** Password update and reset */
export const HANDLE_PASSWORD_RESET_REQUEST = 'HANDLE_PASSWORD_RESET_REQUEST';
export const HANDLE_PASSWORD_RESET_REQUEST_SUCCESS = 'HANDLE_PASSWORD_RESET_REQUEST_SUCCESS';
export const HANDLE_PASSWORD_RESET_REQUEST_FAILED = 'HANDLE_PASSWORD_RESET_REQUEST_FAILED';
